title: Project Daedalus
description: Assistive Technology for Accessible CNC Education
theme: just-the-docs
logo: /assets/logo/logoMecaWhite.png
search_enabled: true
aux_links:
  "GitHub Repository":
    - "https://github.com/MecaChronos9461/Project-Daedalus"
